@base_url = http://localhost
@port = 3000
@url = {{base_url}}:{{port}}/api
# @url = https://currency-converter-api-production.up.railway.app/api
@accessToken = 
@refreshToken = 

### Auth0 Machine to Machine
POST https://siwat-dev.us.auth0.com/oauth/token HTTP/1.1
Content-Type: application/json

{
	"client_id": "nUnIxQSTazQ4PBALWoznljhjJBSqDElI",
	"client_secret": "tUMH7NciLnaCTcA2ZGWIhWO86JM1kb8MBkSE0k-OT-643_5ppv3RxtqGYAGJuB2c",
	"audience": "https://currency-converter-api",
	"grant_type": "client_credentials"
}

### SignIn
POST {{url}}/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "username",
    "password": "P@ssw0rd"
}

### Refresh token
POST {{url}}/auth/refreshToken HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

{
    "refreshToken": "{{refreshToken}}"
}

### SignUp
POST {{url}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@email.com",
    "username": "username",
    "password": "P@ssw0rd"
}

### *********************** USER SERVICE ********************************
### Read user
GET {{url}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update user
PATCH {{url}}/user/35 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "admin",
    "email": "admin@email.com",
    "username": "username",
    "password": "P@ssw0rd"
}

### Update user image
PATCH {{url}}/user/35 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{accessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="profile.png"
Content-Type: image/png

< ./src/assets/mock/profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update role user
PATCH {{url}}/user/role/35 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "role": "admin"
}

### *********************** CURRENCY SERVICE ****************************
### Create currency
POST {{url}}/currency HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "INR",
    "country": "India"
}

### Read currency
GET {{url}}/currency?include=exchange-rate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update currency
PATCH {{url}}/currency/22 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": 123
}

### Delete currency
DELETE  {{url}}/currency/21 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### *********************** EXCHANGE RATE SERVICE ***********************
### Create exchange-rate
POST {{url}}/exchange-rate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "rate": 10,
    "fromCurrency": 22,
    "toCurrency": 21
}

### Read exchange-rate
GET {{url}}/exchange-rate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update exchange-rate
PATCH  {{url}}/exchange-rate/149 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "rate": 1
}

### Delete exchange-rate
DELETE  {{url}}/exchange-rate/149 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}