version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3030'
    env_file: ${ENV_FILE}
    restart: always
    networks:
      - nest_network
      
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - '80:80'
    depends_on:
      - nest-app
    networks:
      - nest_network

networks:
  nest_network:
    name: host_nestjs
    driver: bridge
